In [2]:
import numpy as np 

arr = np.array([[[1,2],[3,4]],[[5,6],[2,4]]])
print(arr)


[[[1 2]
  [3 4]]

 [[5 6]
  [2 4]]]


In [8]:
arr = np.array([[[1,2,3],[2,4,2]],[[3,6,5],[4,8,9]]])
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



int32
(2, 2, 3)
3
12
[[[1. 2. 3.]
  [2. 4. 2.]]

 [[3. 6. 5.]
  [4. 8. 9.]]]


In [11]:
float_arr = arr.astype(str)
print(float_arr)

[[['1' '2' '3']
  ['2' '4' '2']]

 [['3' '6' '5']
  ['4' '8' '9']]]


In [23]:
a = np.zeros((2,2,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [25]:
b = np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [28]:
c = np.zeros(5)
print(c)

[0. 0. 0. 0. 0.]


In [29]:
d = np.linspace(0,10,5)
print(d)

[ 0.   2.5  5.   7.5 10. ]


In [40]:
a1 = np.zeros((2,2,3))
print(a1)
print(a1.shape)
print(a1.size)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
12


In [39]:
a2 = np.zeros((2,2))
print(a2[0,1])

a2[0,0] = 5
print(a2)

print(a2.sum())

0.0
[[5. 0.]
 [0. 0.]]
5.0


In [46]:
shape = np.array([1,2,3,4,5,6,7,8])
re_shape = shape.reshape((2,4))
print(re_shape)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
o = np.ones((2,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
o[0,3] = 6
print(o)

[[1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1.]]


In [54]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

new_array = np.delete(arr, 1, axis=1)

print(new_array)


[[1 3]
 [4 6]
 [7 9]]


In [56]:
matrix = np.eye(3,3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
r = np.random.random((2,2))
print(r)

[[0.06153249 0.19617984]
 [0.46477197 0.99862468]]


In [2]:
b = np.array([3, 1, 4, 2])
print(np.sort(b))

[1 2 3 4]


In [5]:
c = np.array([1, 2, 3, 4, 5, 6])
print(c.reshape(2, 3))

print(c.ndim)

[[1 2 3]
 [4 5 6]]
1


In [6]:
indx = np.array([10,40,20,30])
arr_indx = [1,3]

rslt = indx[arr_indx]
print(rslt)

[40 30]


In [7]:
print(indx[2])

20


In [14]:
m_arr = np.array([[1, 2], [3, 4], [5, 6]])

print(m_arr)

print(m_arr[[0, 1], [1, 0]])

[[1 2]
 [3 4]
 [5 6]]
[2 3]


In [12]:
fancy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(fancy)

rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])
print(fancy[rows, cols])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 5 7]


In [8]:
z = np.array([10, 20, 30, 40])
con = z > 20
print(z[con])

[30 40]


In [10]:
z1 = np.array([[1, 2], [3, 4]])

print(z1)
print(np.linalg.inv(z1))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
